language: python
python:
  - "3.7"
cache:
  directories:
    - $HOME/.cache/pip

addons:
  sonarcloud:
    organization: "d641593"
    token:
      secure: "a82b82382048e230a8f4889588682a2396308f40"
      
install:
  - pip install -r requirements.txt

script: 
  - coverage erase
  - coverage run -m --branch unittest discover -s test -p *Test.py
  - coverage xml -i
  - sonar-scanner -D"sonar.login=a82b82382048e230a8f4889588682a2396308f40"
