language: python
python:
  - "3.7"
cache:
  directories:
    - $HOME/.cache/pip
# command to install dependencies
before_install:
  -wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
  -unzip sonar-scanner-cli-3.3.0.1492-linux.zip -d /tmp
install:
  - pip install -r requirements.txt
# command to run tests
script: 
  - python ./PointCalculationTest.py
  - /tmp/sonar-scanner-3.3.0.1492-linux/bin/sonar-scanner.bat -D"sonar.projectKey=D0641593" -D"sonar.sources=." -D"sonar.host.url=http://140.134.24.239:9000" -D"sonar.login=b6eea023dbf8bc6f615098e40c9148cd50eb7d27"