language: python
python:
  - "3.7"
cache:
  directories:
    - $HOME/.cache/pip
# command to install dependencies
addons:
  sonarCloud:
    organization: $SONAR_HOST_URL # 
    token:
      secure: $SONAR_TOKEN # encrypted value of your token
install:
  - pip install -r requirements.txt
# command to run tests
script: 
  - python ./PointCalculationTest.py
  - sonar-scanner.bat -Dsonar.projectKey="D0641593" -D"sonar.sources=." -D"sonar.host.url=http://140.134.24.239:9000" -D"sonar.login=b6eea023dbf8bc6f615098e40c9148cd50eb7d27"