language: python
python:
  - "3.7"
cache:
  directories:
    - $HOME/.cache/pip
# command to install dependencies
addons:
  sonarcloud:
    organization: SONAR_HOST_URL # the key of the org you chose at step #3
    token:
      secure: SONAR_TOKEN # encrypted value of your token
install:
  - pip install -r requirements.txt
# command to run tests
script: 
  - python ./PointCalculationTest.py
  - sonar-scanner -Dsonar.project="D0641593"